#! /bin/bash

export LD_LIBRARY_PATH=/usr/x86_64-linux-gnu

i="$(echo "$1" | sed -e "s/viewtube://" -e "s/SEPARATOR/|/g")"
v="$(echo "$i" | cut -d "|" -f 1 -s)"
a="$(echo "$i" | cut -d "|" -f 2 -s)"
s="$(echo "$i" | cut -d "|" -f 3 -s)"
if [ "$v" = "" ]; then
	v="$i"
fi
if [ "$a" = "" ]; then
	if [ "$s" = "" ]; then
		mpv --osc --fs "$v" || cvlc -f "$v"
	else
		mpv --osc --fs --sub-file="$s" "$v" || cvlc -f --sub-file="$s" "$v"
	fi
else
	if [ "$s" = "" ]; then
		mpv --osc --fs --audio-file="$a" "$v" || cvlc -f --input-slave="$a" "$v"
	else
		mpv --osc --fs --sub-file="$s" --audio-file="$a" "$v" || cvlc -f --sub-file="$s" --input-slave="$a" "$v"
	fi
fi
